### PR TITLE
Add support for Cap 3.

### PR DESCRIPTION
**Pull request by rroblak**
Remove extraneous code related to previous versions.

### CODE REVIEW

**Comment by smith** [comment]
Thanks for doing this. I'm ready to merge and make this the new master once we do the following:
- [x] Update the current README to say that newer versions support Cap 3
- [x] Do a major version bump
- [x] Update the README on master to point Cap 2 users back to previous versions
- [x] Fix or remove the Travis build

**Comment by smith** [comment]
@rroblak are you still open to helping get this done? Let me know if you need me to do any of the steps. Thanks!

**Comment by rroblak** [comment]
@smith Yes I am, just had a really busy last couple of weeks.  I'll see if I can get to those things tomorrow.

**Comment by rroblak** [comment]
@smith I made the requested changes.  The Travis build was already removed from the README— is there any else that needs to be done that?

Also, if you could release a new gem or add me on rubygems that would be great :)

**Comment by rorcraft** [comment]
+1

**Comment by smith** [comment]
@rroblak v1.0.0 has been published and I've added you as an owner on RubyGems. Please let me know if there's anything else I can do to help. Thanks!

**Pull request merged**
